#############################################################################
# Makefile for building: mySMTPSvr.app/Contents/MacOS/mySMTPSvr
# Generated by qmake (3.1) (Qt 5.13.1)
# Project:  mySMTPSvr.pro
# Template: app
# Command: /usr/local/Cellar/qt/5.13.1/bin/qmake -o Makefile mySMTPSvr.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.13.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.13.1/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/AGL.framework/Headers/ -I. -I/usr/local/Cellar/qt/5.13.1/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.13.1/lib
QMAKE         = /usr/local/Cellar/qt/5.13.1/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/Cellar/qt/5.13.1/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/Cellar/qt/5.13.1/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = mySMTPSvr1.0.0
DISTDIR = /Users/renlei/Qt-workspace/mySMTPSvr/.tmp/mySMTPSvr1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wl,-rpath,@executable_path/../Frameworks
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/5.13.1/lib -framework QtWidgets -framework QtGui -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		dialog.cpp moc_dialog.cpp
OBJECTS       = main.o \
		dialog.o \
		moc_dialog.o
DIST          = /usr/local/Cellar/qt/5.13.1/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/qml_debug.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/lex.prf \
		mySMTPSvr.pro dialog.h main.cpp \
		dialog.cpp
QMAKE_TARGET  = mySMTPSvr
DESTDIR       = 
TARGET        = mySMTPSvr.app/Contents/MacOS/mySMTPSvr

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.14
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/renlei/Qt-workspace/mySMTPSvr/mySMTPSvr.pro


include /usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

mySMTPSvr.app/Contents/MacOS/mySMTPSvr: ui_dialog.h $(OBJECTS)  
	@test -d mySMTPSvr.app/Contents/MacOS/ || mkdir -p mySMTPSvr.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: mySMTPSvr.pro /usr/local/Cellar/qt/5.13.1/mkspecs/macx-clang/qmake.conf /usr/local/Cellar/qt/5.13.1/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/qml_debug.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.13.1/mkspecs/features/lex.prf \
		mySMTPSvr.pro \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/QtWidgets.prl \
		/usr/local/Cellar/qt/5.13.1/lib/QtGui.framework/QtGui.prl \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/QtNetwork.prl \
		/usr/local/Cellar/qt/5.13.1/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile mySMTPSvr.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
/usr/local/Cellar/qt/5.13.1/mkspecs/features/spec_pre.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/qdevice.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/5.13.1/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/5.13.1/mkspecs/common/macx.conf:
/usr/local/Cellar/qt/5.13.1/mkspecs/common/sanitize.conf:
/usr/local/Cellar/qt/5.13.1/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/5.13.1/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt/5.13.1/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/5.13.1/mkspecs/common/clang-mac.conf:
/usr/local/Cellar/qt/5.13.1/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_bodymovin_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_charts.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_core.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_graphics_support_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_help.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_location.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_macextras.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_macextras_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_network.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_script.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webview.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/macx-clang/qmake.conf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/toolchain.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/toolchain.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/resolve_config.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/qml_debug.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/mac.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/unix/opengl.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/qmake_use.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/file_copies.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/testcase_targets.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/exceptions.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/5.13.1/mkspecs/features/lex.prf:
mySMTPSvr.pro:
/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/QtWidgets.prl:
/usr/local/Cellar/qt/5.13.1/lib/QtGui.framework/QtGui.prl:
/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/QtNetwork.prl:
/usr/local/Cellar/qt/5.13.1/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile mySMTPSvr.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

mySMTPSvr.app/Contents/PkgInfo: 
	@test -d mySMTPSvr.app/Contents || mkdir -p mySMTPSvr.app/Contents
	@$(DEL_FILE) mySMTPSvr.app/Contents/PkgInfo
	@echo "APPL????" > mySMTPSvr.app/Contents/PkgInfo
mySMTPSvr.app/Contents/Resources/empty.lproj: 
	@test -d mySMTPSvr.app/Contents/Resources || mkdir -p mySMTPSvr.app/Contents/Resources
	@touch mySMTPSvr.app/Contents/Resources/empty.lproj
	
mySMTPSvr.app/Contents/Info.plist: 
	@test -d mySMTPSvr.app/Contents || mkdir -p mySMTPSvr.app/Contents
	@$(DEL_FILE) mySMTPSvr.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,ray.mySMTPSvr,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},ray.mySMTPSvr,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.12,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,mySMTPSvr,g" -e "s,@LIBRARY@,mySMTPSvr,g" -e "s,\$${EXECUTABLE_NAME},mySMTPSvr,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /usr/local/Cellar/qt/5.13.1/mkspecs/macx-clang/Info.plist.app >mySMTPSvr.app/Contents/Info.plist

all: Makefile \
		mySMTPSvr.app/Contents/PkgInfo \
		mySMTPSvr.app/Contents/Resources/empty.lproj \
		mySMTPSvr.app/Contents/Info.plist mySMTPSvr.app/Contents/MacOS/mySMTPSvr

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/Cellar/qt/5.13.1/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents dialog.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp dialog.cpp $(DISTDIR)/
	$(COPY_FILE) --parents dialog.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r mySMTPSvr.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode $(EXPORT__PRO_FILE_) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/Cellar/qt/5.13.1/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.12 -Wall -W -dM -E -o moc_predefs.h /usr/local/Cellar/qt/5.13.1/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_dialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dialog.cpp
moc_dialog.cpp: dialog.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qdialog.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/QTcpServer \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qtcpserver.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/QTcpSocket \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.13.1/bin/moc
	/usr/local/Cellar/qt/5.13.1/bin/moc $(DEFINES) --include /Users/renlei/Qt-workspace/mySMTPSvr/moc_predefs.h -I/usr/local/Cellar/qt/5.13.1/mkspecs/macx-clang -I/Users/renlei/Qt-workspace/mySMTPSvr -I/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.13.1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.13.1/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/10.0.1/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -F/usr/local/Cellar/qt/5.13.1/lib dialog.h -o moc_dialog.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_dialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_dialog.h
ui_dialog.h: dialog.ui \
		/usr/local/Cellar/qt/5.13.1/bin/uic
	/usr/local/Cellar/qt/5.13.1/bin/uic dialog.ui -o ui_dialog.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp dialog.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qdialog.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/QTcpServer \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qtcpserver.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/QTcpSocket \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

dialog.o: dialog.cpp dialog.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/QDialog \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qdialog.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/QTcpServer \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qtcpserver.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/QTcpSocket \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		ui_dialog.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/QtNetwork \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qtnetworkglobal.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qabstractnetworkcache.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qabstractsocket.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qauthenticator.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qdnslookup.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qdtls.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qhostaddress.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qhostinfo.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qhstspolicy.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qhttpmultipart.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qlocalserver.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qlocalsocket.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qnetworkconfigmanager.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qnetworkconfiguration.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qnetworkcookie.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qnetworkcookiejar.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qnetworkdatagram.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qnetworkdiskcache.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qnetworkinterface.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qnetworkproxy.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qnetworkrequest.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qnetworksession.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qocspresponse.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qpassworddigestor.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qsctpserver.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qsctpsocket.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qssl.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qsslcertificate.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qsslcertificateextension.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qsslcipher.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qsslconfiguration.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qssldiffiehellmanparameters.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qsslellipticcurve.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qsslerror.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qsslkey.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qsslpresharedkeyauthenticator.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qsslsocket.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qudpsocket.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtNetwork.framework/Headers/qtnetworkversion.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/QMessageBox \
		/usr/local/Cellar/qt/5.13.1/lib/QtWidgets.framework/Headers/qmessagebox.h \
		/usr/local/Cellar/qt/5.13.1/lib/QtGui.framework/Headers/QPixmap \
		/usr/local/Cellar/qt/5.13.1/lib/QtGui.framework/Headers/qpixmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/mySMTPSvr/bin || mkdir -p $(INSTALL_ROOT)/opt/mySMTPSvr/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/mySMTPSvr/bin/mySMTPSvr.app
	
	-$(QINSTALL) mySMTPSvr.app $(INSTALL_ROOT)/opt/mySMTPSvr/bin/mySMTPSvr.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/mySMTPSvr/bin/mySMTPSvr.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/mySMTPSvr/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

